# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Fourre-tout
tagline:          'A bit of everything'
description:      'Some notes, some thoughts, some ideas'
url:              https://bcrestel.github.io
baseurl:          

author:
  name:           'Ben C'

emailme:          mailto:ben.crestel@zoho.com

plugins:
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-gist
paginate:         5

# Custom vars
github_username:  bcrestel
linkedin_username: bcrestel
