# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Fourre-tout
tagline:          'A bit of everything'
description:      'Some notes, some ideas, some tricks'
url:              https://bcrestel.github.io
baseurl:          /

author:
  name:           'Ben C'

emailme:          mailto:ben.crestel@zoho.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-gist]
paginate:         5

# Custom vars
github_username:  bcrestel
linkedin_username: crestel
